services:
  frontend:
    build:
      context: ./frontend
      args:
        CACHE_BUSTER: ${CACHE_BUSTER:-$(date +%s)}
        VITE_API_URL: http://localhost:8000/
    ports:
      - "80:80"
  backend:
    build:
      context: ./backend
      args:
        CACHE_BUSTER: ${CACHE_BUSTER:-$(date +%s)}
    environment:
      DB_HOST: db
      CORS_ORIGINS: http://localhost
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  db:
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres
    env_file: ".env"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "telemedicina_db" ]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  postgres_data:
